spring.application.name=photory

#DB接続設定
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/photory
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA設定
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ファイルアップロード上限
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# 画像保存先
app.upload.dir=uploads/images

# Thymeleaf（開発中はキャッシュOFF）
spring.thymeleaf.cache=false

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email